# Generated by Django 3.2.16 on 2023-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20230507_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrapper',
            options={'verbose_name': 'объект "Обёртка"', 'verbose_name_plural': 'Обёртки'},
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='title',
            field=models.CharField(help_text='Уникальное название обертки, не более 256 символов', max_length=256, verbose_name='Название'),
        ),
    ]
